image: registry.salsa.debian.org/salsa-ci-team/ci-image-git-buildpackage:latest

pages:
  stage: deploy
  except:
    - tags
  artifacts:
    paths:
    - public
  script:
   - gitlab-ci-git-buildpackage-all
   - gitlab-ci-aptly
