name: Build Debian Packages with Debcraft
run-name: Build Debian Packages with Debcraft
on:
  workflow_dispatch:

jobs:
  build-debs:
    name: build-debs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # , bullseye
        codename: [sid, trixie, bookworm]
        # , arm64, armhf
        arch: [amd64]
    steps:
      - name: checkout package sources
        uses: actions/checkout@v4
        with:
          # this is required for gbp to work properly
          fetch-tags: true
      
      - name: checkout debcraft
        uses: actions/checkout@v4
        with:
          # https://github.com/ottok/debcraft
          repository: ottok/debcraft
          path: /tmp/debcraft
          ref: 512b4c356c842ecf7aecb81d23cb4947a910942a
    
      - name: install required software
        run: sudo apt install -y make podman

      - name: install debcraft
        working-directory: /tmp/debcraft
        run: make install-local

      - name: run build
        run: $HOME/.local/bin/debcraft build --distribution ${{ matrix.codename }}

      - name: save artifact
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.codename }}
          path: /tmp/debcraft-build-mtools-*/
